networks:
  laravel:

services:
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    links:
      - php

  mysql:
    image: mysql:latest
    container_name: laravel_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: miguel30
      MYSQL_PASSWORD: miguel30
      MYSQL_USER: miguel30
      MYSQL_DATABASE: perfect-pay-docker
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
